python render.py --subject bala --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject biden --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject justin --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject malte_1 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject marcel --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject nf_01 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject nf_03 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject wojtek_1 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/INSTA --white_bg
python render.py --subject subject1 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/HR --white_bg
python render.py --subject subject2 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/HR --white_bg
python render.py --subject subject3 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/HR --white_bg
python render.py --subject subject4 --work_name bbw_2000_covarience_shear0125_dX --output_dir output/HR --white_bg